[package]
name = "noughts_and_crosses_lib"
version = "0.0.3"
authors = ["Ethan Brierley <ethanboxx@gmail.com>"]
license = "MIT/Apache-2.0"
description = """
Game of tic tac toe
"""
[dependencies]
rand = "0.5"